#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 3
#SBATCH -t 8:00:00
#SBATCH -J 09_dex
#SBATCH --mail-type=ALL
#SBATCH --mail-user henrikssonnelliie@gmail.com
#SBATCH --output=R-job.out
# Load modules
module load bioinfo-tools
module load R
module load R_packages/4.1.1

Rscript 09_difexpression
